---

# Directory that will be used as the location for the download
dest_path: "/tmp"

# This NRPE package is only used for the plugin, as the nrpe plugin on some distributions
# require the distributions Nagios package to be installed.
pluginstarball: nagios-plugins-2.2.1.tar.gz
pluginssrc: nagios-plugins-2.2.1

# Location of monitoring plugins
plugins_dir: /usr/local/nagios/libexec
